[package]
name = "photorganizer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
kamadak-exif = "0.5.4"
walkdir = "2.3.2"
log = "0.4.14"
pretty_env_logger = "0.4.0"
rayon = "1.5.1"
